version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "> 12.11.6, < 12.12"
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.3, < 12.13"
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
  - dependency-name: karma
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.3.1
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.901.14
  - dependency-name: y18n
    versions:
    - 4.0.1
