version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: "@angular/language-service"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/cli"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular-devkit/build-angular"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/animations"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/common"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/compiler"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/core"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/forms"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/localize"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/platform-browser"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/platform-browser-dynamic"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/platform-server"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular/router"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "angular-pipes"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "@types/jasmine"
        update-types: [ "version-update:semver-patch" ]
