version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 25
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-eslint/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-devkit/*"
        update-types: [ "version-update:semver-major" ]
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"
          - "@angular-devkit/*"
        update-types:
          - "minor"
          - "patch"
      typescript-eslint:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - "typescript-eslint/*"
      jasmine:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - "jasmine-*"


