version: 1
update_configs:
  - package_manager: "javascript"
    version_requirement_updates: "increase_versions"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_name: "@types/node"
          update_type: "semver:minor"
      - match:
          dependency_name: "ts-node"
      - match:
          dependency_name: "mocha"
      - match:
          dependency_name: "chai"
      - match:
          dependency_name: "typescript"
      - match:
          dependency_name: "music-metadata-browser"
          update_type: "semver:patch"
      - match:
          dependency_name: "@types/jasmine"
      - match:
          dependency_name: "ts-node"
      - match:
          dependency_name: "core-js"
      - match:
          dependency_name: "@angular/common"
          update_type: "semver:minor"
      - match:
          dependency_name: "@angular/forms"
          update_type: "semver:minor"
      - match:
          dependency_name: "@angular/http"
          update_type: "semver:minor"
      - match:
          dependency_name: "@angular/language-service"
          update_type: "semver:minor"
      - match:
          dependency_name: "@angular-devkit/build-angular"
          update_type: "semver:minor"
      - match:
          dependency_name: "@angular/cli"
          update_type: "semver:minor"
      - match:
          dependency_name: "codelyzer"
      - match:
          dependency_name: "karma-jasmine"
      - match:
          dependency_name: "karma-jasmine-html-reporter"
      - match:
          dependency_name: "protractor"
