name: Build web application
on: push

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Angular client
        run: yarn global add @angular/cli

      - name: Install dependencies
        run: yarn install

      - name: Angular code analysis
        run: yarn lint

      - name: Angular build
        run: ng build
